const Images = {
  // require('../assets/images/danger.png')
  fistImg: require('../assest/Imageses/fistImg.png'),
  flag: require('../assest/Imageses/flag.png'),
  thirdImg: require('../assest/Imageses/ThirdImg.png'),
  dropdownarrow: require('../assest/Imageses/dropdownarrow.png'),
  pen: require("../assest/Imageses/pen.png"),
  bell: require("../assest/Imageses/bell.png"),
  profile : require("../assest/Imageses/profile.png"),
  menu: require("../assest/Imageses/menu.png"),
  SliderImg: require("../assest/Imageses/SliderImg.png"),
  shopping: require("../assest/Imageses/shopping.png"),
  right: require("../assest/Imageses/Right.png"),
  man: require("../assest/Imageses/Man.png"),
  girl: require("../assest/Imageses/Girl.png"),
  kids: require("../assest/Imageses/kids.png"),
  wedding: require("../assest/Imageses/Wedding.png"),
  timer: require("../assest/Imageses/Timer.png"),
  ring: require("../assest/Imageses/Ring.png"),
  backarrow: require("../assest/Imageses/backarrow.png"),
  // banjaralogo: require("../assest/Imageses/banjaraLogo.png"),
  newbackarrow: require("../assest/Imageses/newbackarrow.png"),
  female: require("../assest/Imageses/female.png"),
  Male: require("../assest/Imageses/Mangender.png"), 
  uploadImg: require("../assest/Imageses/uploadImage.png"),    // dropdownarrow: require('../assets/images/.png'),
  addPic: require("../assest/Imageses/AddPic.png"), 
  marimonyprofile: require("../assest/Imageses/MarimonyProfile.png"),
  editlogo: require("../assest/Imageses/editlogo.png"), 
  matrimonyBackarrow: require("../assest/Imageses/matrimonyBackarrow.png"), 
  shopbag: require("../assest/Imageses/shopbag.png"), 
  rightarrow: require("../assest/Imageses/Rightarrow.png"),
  footerImg: require("../assest/Imageses/FooterImg.png"),
  circlearrow: require("../assest/Imageses/circlearrow.png"),
  backarrow2: require("../assest/Imageses/backarrow2.png"),
  banjaraworld: require("../assest/Imageses/banjaraworld.png"),
  heart: require("../assest/Imageses/heardImg.jpg"),
  heartFilled: require("../assest/Imageses/fillheart.jpg"),
  SmileEmoji: require("../assest/Imageses/SmileEmoji.png"),
  NotificationBell: require("../assest/Imageses/notificationbell.png"),
  menuIcon: require("../assest/Imageses/menuimg.png"),

};
export default Images;
 